services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    volumes:
      - desafio_db_data:/var/lib/postgresql/data
      - ./db-config:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: api_desafio
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db

volumes:
  desafio_db_data: