services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    volumes:
      - desafio_db_data:/var/lib/postgresql/data
      - ./db-config:/docker-entrypoint-initdb.d

volumes:
  desafio_db_data: